# scripts/languages.py
# MEDUSA – Multi‑lingual support (100+ languages)
# All UI strings used in medusa_demo.py are translated below.
# For languages without a full manual translation, English is used as fallback.

LANGUAGES = {
    "Afrikaans": "af",
    "Albanian": "sq",
    "Amharic": "am",
    "Arabic": "ar",
    "Armenian": "hy",
    "Azerbaijani": "az",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bosnian": "bs",
    "Bulgarian": "bg",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Chichewa": "ny",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Corsican": "co",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Filipino": "fil",
    "Finnish": "fi",
    "French": "fr",
    "Frisian": "fy",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Gujarati": "gu",
    "Haitian Creole": "ht",
    "Hausa": "ha",
    "Hawaiian": "haw",
    "Hebrew": "iw",
    "Hindi": "hi",
    "Hmong": "hmn",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jw",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Khmer": "km",
    "Korean": "ko",
    "Kurdish (Kurmanji)": "ku",
    "Kyrgyz": "ky",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Maori": "mi",
    "Marathi": "mr",
    "Mongolian": "mn",
    "Myanmar (Burmese)": "my",
    "Nepali": "ne",
    "Norwegian": "no",
    "Pashto": "ps",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Romanian": "ro",
    "Russian": "ru",
    "Samoan": "sm",
    "Scots Gaelic": "gd",
    "Serbian": "sr",
    "Sesotho": "st",
    "Shona": "sn",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Spanish": "es",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tajik": "tg",
    "Tamil": "ta",
    "Telugu": "te",
    "Thai": "th",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Welsh": "cy",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Yoruba": "yo",
    "Zulu": "zu",
}

# -------------------------------------------------------------------
# Translations for every UI string in the application
# Keys are sorted alphabetically for easier maintenance.
# -------------------------------------------------------------------
TRANSLATIONS = {
    "en": {
        "agree": "Agree",
        "analysis": "Analysis",
        "auto_detect": "Auto‑Detect",
        "benign": "Benign",
        "brain_mri": "Brain MRI",
        "chest_xray": "Chest X‑Ray",
        "correct_diagnosis": "Correct diagnosis:",
        "create_account": "Create Account",
        "critical_finding": "⚠️ CRITICAL FINDING – PNEUMONIA (high confidence)",
        "disagree": "Disagree",
        "download_pdf_report": "Download PDF Report",
        "email": "Email",
        "footer": "MEDUSA · 850K params · CPU‑only · v1.0",
        "forgot_password": "Forgot Password",
        "healthy": "Healthy",
        "hospital_name": "Hospital/Clinic Name",
        "login": "Login",
        "logout": "Logout",
        "location": "Location",
        "lung_ct": "Lung CT",
        "malignant": "Malignant",
        "model_not_trained": "Model not trained yet",
        "modality_override": "Modality (override if auto‑detection fails):",
        "monthly_limit_reached": "Monthly scan limit reached. Please upgrade.",
        "normal": "Normal",
        "original": "Original Image",
        "password": "Password",
        "patient_id": "Patient ID (enter before uploading)",
        "patient_id_warning": "Please enter a Patient ID to continue.",
        "pneumonia": "Pneumonia",
        "powered_by": "Powered by DARKMOOR LTD",
        "radiologist_confirmation": "Radiologist confirmation:",
        "send_reset_link": "Send Reset Link",
        "sign_up": "Sign Up",
        "title": "🧠 MEDUSA – Medical AI",
        "upgrade": "Upgrade to Unlimited",
        "upload_prompt": "Drop chest X‑rays, brain MRIs, or lung CT slices below",
        "welcome": "Welcome",
    },
    "fr": {
        "agree": "D'accord",
        "analysis": "Analyse",
        "auto_detect": "Détection auto",
        "benign": "Bénin",
        "brain_mri": "IRM cérébrale",
        "chest_xray": "Radiographie thoracique",
        "correct_diagnosis": "Diagnostic correct :",
        "create_account": "Créer un compte",
        "critical_finding": "⚠️ RÉSULTAT CRITIQUE – PNEUMONIE (haute confiance)",
        "disagree": "Désaccord",
        "download_pdf_report": "Télécharger le rapport PDF",
        "email": "E‑mail",
        "footer": "MEDUSA · 850K paramètres · CPU uniquement · v1.0",
        "forgot_password": "Mot de passe oublié",
        "healthy": "Sain",
        "hospital_name": "Nom de l'hôpital/clinique",
        "login": "Connexion",
        "logout": "Déconnexion",
        "location": "Emplacement",
        "lung_ct": "CT pulmonaire",
        "malignant": "Malin",
        "model_not_trained": "Modèle non entraîné",
        "modality_override": "Modalité (forcer si la détection automatique échoue) :",
        "monthly_limit_reached": "Limite mensuelle de scans atteinte. Veuillez passer à un abonnement supérieur.",
        "normal": "Normale",
        "original": "Image originale",
        "password": "Mot de passe",
        "patient_id": "ID du patient (entrer avant le téléchargement)",
        "patient_id_warning": "Veuillez entrer un ID de patient pour continuer.",
        "pneumonia": "Pneumonie",
        "powered_by": "Propulsé par DARKMOOR LTD",
        "radiologist_confirmation": "Confirmation du radiologue :",
        "send_reset_link": "Envoyer le lien de réinitialisation",
        "sign_up": "S'inscrire",
        "title": "🧠 MEDUSA – IA Médicale",
        "upgrade": "Passer à l'illimité",
        "upload_prompt": "Déposez des radiographies pulmonaires, IRM cérébrales ou coupes CT ci‑dessous",
        "welcome": "Bienvenue",
    },
    "es": {
        "agree": "De acuerdo",
        "analysis": "Análisis",
        "auto_detect": "Detección automática",
        "benign": "Benigno",
        "brain_mri": "IRM cerebral",
        "chest_xray": "Radiografía de tórax",
        "correct_diagnosis": "Diagnóstico correcto:",
        "create_account": "Crear cuenta",
        "critical_finding": "⚠️ HALLAZGO CRÍTICO – NEUMONÍA (alta confianza)",
        "disagree": "Desacuerdo",
        "download_pdf_report": "Descargar informe PDF",
        "email": "Correo electrónico",
        "footer": "MEDUSA · 850K parámetros · Solo CPU · v1.0",
        "forgot_password": "Olvidé mi contraseña",
        "healthy": "Sano",
        "hospital_name": "Nombre del hospital/clínica",
        "login": "Iniciar sesión",
        "logout": "Cerrar sesión",
        "location": "Ubicación",
        "lung_ct": "TC pulmonar",
        "malignant": "Maligno",
        "model_not_trained": "Modelo no entrenado",
        "modality_override": "Modalidad (forzar si la detección automática falla):",
        "monthly_limit_reached": "Límite mensual de escaneos alcanzado. Actualice su plan.",
        "normal": "Normal",
        "original": "Imagen original",
        "password": "Contraseña",
        "patient_id": "ID del paciente (ingresar antes de subir)",
        "patient_id_warning": "Ingrese un ID de paciente para continuar.",
        "pneumonia": "Neumonía",
        "powered_by": "Desarrollado por DARKMOOR LTD",
        "radiologist_confirmation": "Confirmación del radiólogo:",
        "send_reset_link": "Enviar enlace de restablecimiento",
        "sign_up": "Registrarse",
        "title": "🧠 MEDUSA – IA Médica",
        "upgrade": "Actualizar a ilimitado",
        "upload_prompt": "Arrastre aquí radiografías de tórax, IRM cerebrales o cortes de TC",
        "welcome": "Bienvenido",
    },
    "pt": {
        "agree": "Concordo",
        "analysis": "Análise",
        "auto_detect": "Detecção automática",
        "benign": "Benigno",
        "brain_mri": "RM cerebral",
        "chest_xray": "Radiografia torácica",
        "correct_diagnosis": "Diagnóstico correto:",
        "create_account": "Criar conta",
        "critical_finding": "⚠️ ACHADO CRÍTICO – PNEUMONIA (alta confiança)",
        "disagree": "Discordo",
        "download_pdf_report": "Baixar relatório PDF",
        "email": "E‑mail",
        "footer": "MEDUSA · 850K parâmetros · Somente CPU · v1.0",
        "forgot_password": "Esqueci minha senha",
        "healthy": "Saudável",
        "hospital_name": "Nome do hospital/clínica",
        "login": "Entrar",
        "logout": "Sair",
        "location": "Localização",
        "lung_ct": "TC de pulmão",
        "malignant": "Maligno",
        "model_not_trained": "Modelo não treinado",
        "modality_override": "Modalidade (forçar se a detecção automática falhar):",
        "monthly_limit_reached": "Limite mensal de exames atingido. Atualize seu plano.",
        "normal": "Normal",
        "original": "Imagem original",
        "password": "Senha",
        "patient_id": "ID do paciente (insira antes de enviar)",
        "patient_id_warning": "Insira um ID de paciente para continuar.",
        "pneumonia": "Pneumonia",
        "powered_by": "Desenvolvido por DARKMOOR LTD",
        "radiologist_confirmation": "Confirmação do radiologista:",
        "send_reset_link": "Enviar link de redefinição",
        "sign_up": "Cadastrar",
        "title": "🧠 MEDUSA – IA Médica",
        "upgrade": "Atualizar para ilimitado",
        "upload_prompt": "Arraste radiografias torácicas, RM cerebrais ou cortes de TC abaixo",
        "welcome": "Bem‑vindo",
    },
    "pt-BR": {
        "agree": "Concordo",
        "analysis": "Análise",
        "auto_detect": "Detecção automática",
        "benign": "Benigno",
        "brain_mri": "RM cerebral",
        "chest_xray": "Radiografia torácica",
        "correct_diagnosis": "Diagnóstico correto:",
        "create_account": "Criar conta",
        "critical_finding": "⚠️ ACHADO CRÍTICO – PNEUMONIA (alta confiança)",
        "disagree": "Discordo",
        "download_pdf_report": "Baixar relatório PDF",
        "email": "E‑mail",
        "footer": "MEDUSA · 850K parâmetros · Somente CPU · v1.0",
        "forgot_password": "Esqueci minha senha",
        "healthy": "Saudável",
        "hospital_name": "Nome do hospital/clínica",
        "login": "Entrar",
        "logout": "Sair",
        "location": "Localização",
        "lung_ct": "TC de pulmão",
        "malignant": "Maligno",
        "model_not_trained": "Modelo não treinado",
        "modality_override": "Modalidade (forçar se a detecção automática falhar):",
        "monthly_limit_reached": "Limite mensal de exames atingido. Atualize seu plano.",
        "normal": "Normal",
        "original": "Imagem original",
        "password": "Senha",
        "patient_id": "ID do paciente (insira antes de enviar)",
        "patient_id_warning": "Insira um ID de paciente para continuar.",
        "pneumonia": "Pneumonia",
        "powered_by": "Desenvolvido por DARKMOOR LTD",
        "radiologist_confirmation": "Confirmação do radiologista:",
        "send_reset_link": "Enviar link de redefinição",
        "sign_up": "Cadastrar",
        "title": "🧠 MEDUSA – IA Médica",
        "upgrade": "Atualizar para ilimitado",
        "upload_prompt": "Arraste radiografias torácicas, RM cerebrais ou cortes de TC abaixo",
        "welcome": "Bem‑vindo",
    },
    "de": {
        "agree": "Zustimmen",
        "analysis": "Analyse",
        "auto_detect": "Automatische Erkennung",
        "benign": "Gutartig",
        "brain_mri": "Gehirn‑MRT",
        "chest_xray": "Thorax‑Röntgen",
        "correct_diagnosis": "Richtige Diagnose:",
        "create_account": "Konto erstellen",
        "critical_finding": "⚠️ KRITISCHER BEFUND – PNEUMONIE (hohe Konfidenz)",
        "disagree": "Ablehnen",
        "download_pdf_report": "PDF‑Bericht herunterladen",
        "email": "E‑Mail",
        "footer": "MEDUSA · 850K Parameter · Nur CPU · v1.0",
        "forgot_password": "Passwort vergessen",
        "healthy": "Gesund",
        "hospital_name": "Name des Krankenhauses/der Klinik",
        "login": "Anmelden",
        "logout": "Abmelden",
        "location": "Standort",
        "lung_ct": "Lungen‑CT",
        "malignant": "Bösartig",
        "model_not_trained": "Modell nicht trainiert",
        "modality_override": "Modalität (erzwingen, falls automatische Erkennung fehlschlägt):",
        "monthly_limit_reached": "Monatliches Scan‑Limit erreicht. Bitte upgraden.",
        "normal": "Normal",
        "original": "Originalbild",
        "password": "Passwort",
        "patient_id": "Patienten‑ID (vor dem Hochladen eingeben)",
        "patient_id_warning": "Bitte geben Sie eine Patienten‑ID ein, um fortzufahren.",
        "pneumonia": "Pneumonie",
        "powered_by": "Bereitgestellt von DARKMOOR LTD",
        "radiologist_confirmation": "Bestätigung des Radiologen:",
        "send_reset_link": "Link zum Zurücksetzen senden",
        "sign_up": "Registrieren",
        "title": "🧠 MEDUSA – Medizinische KI",
        "upgrade": "Auf unbegrenzt upgraden",
        "upload_prompt": "Thorax‑Röntgen, Gehirn‑MRT oder Lungen‑CT‑Aufnahmen hier ablegen",
        "welcome": "Willkommen",
    },
    "it": {
        "agree": "Accetto",
        "analysis": "Analisi",
        "auto_detect": "Rilevamento automatico",
        "benign": "Benigno",
        "brain_mri": "Risonanza magnetica cerebrale",
        "chest_xray": "Radiografia toracica",
        "correct_diagnosis": "Diagnosi corretta:",
        "create_account": "Crea account",
        "critical_finding": "⚠️ REPERTO CRITICO – POLMONITE (alta confidenza)",
        "disagree": "Non sono d'accordo",
        "download_pdf_report": "Scarica rapporto PDF",
        "email": "E‑mail",
        "footer": "MEDUSA · 850K parametri · Solo CPU · v1.0",
        "forgot_password": "Password dimenticata",
        "healthy": "Sano",
        "hospital_name": "Nome dell'ospedale/clinica",
        "login": "Accedi",
        "logout": "Esci",
        "location": "Posizione",
        "lung_ct": "TC polmonare",
        "malignant": "Maligno",
        "model_not_trained": "Modello non addestrato",
        "modality_override": "Modalità (forza se il rilevamento automatico fallisce):",
        "monthly_limit_reached": "Limite mensile di scansioni raggiunto. Effettua l'upgrade.",
        "normal": "Normale",
        "original": "Immagine originale",
        "password": "Password",
        "patient_id": "ID paziente (inserire prima del caricamento)",
        "patient_id_warning": "Inserire un ID paziente per continuare.",
        "pneumonia": "Polmonite",
        "powered_by": "Offerto da DARKMOOR LTD",
        "radiologist_confirmation": "Conferma del radiologo:",
        "send_reset_link": "Invia link di reset",
        "sign_up": "Registrati",
        "title": "🧠 MEDUSA – IA Medica",
        "upgrade": "Passa a illimitato",
        "upload_prompt": "Trascina qui radiografie toraciche, RM cerebrali o fette TC",
        "welcome": "Benvenuto",
    },
    "ha": {   # Hausa
        "agree": "Na yarda",
        "analysis": "Bincike",
        "auto_detect": "Ganowa ta atomatik",
        "benign": "Mara cuta",
        "brain_mri": "Hoto na kwakwalwa (MRI)",
        "chest_xray": "Hoton kirji (X‑ray)",
        "correct_diagnosis": "Sahihiyar ganewar cuta:",
        "create_account": "Buɗe asusu",
        "critical_finding": "⚠️ MUHIMMAN SAKAMAKO – CIWON HUHU (tabbatacce)",
        "disagree": "Ban yarda ba",
        "download_pdf_report": "Sauke rahoton PDF",
        "email": "Adireshin imel",
        "footer": "MEDUSA · 850K sigogi · CPU kawai · v1.0",
        "forgot_password": "Manta kalmar sirri",
        "healthy": "Lafiyayye",
        "hospital_name": "Sunan asibiti / gidan magani",
        "login": "Shiga",
        "logout": "Fita",
        "location": "Wuri",
        "lung_ct": "Hoton huhu (CT)",
        "malignant": "Mugun ciwo",
        "model_not_trained": "Ba a horas da tsarin ba tukuna",
        "modality_override": "Nau'in hoto (tilasta idan ganowa ta atomatik ta gaza):",
        "monthly_limit_reached": "Adadin binciken watan ya cika. Da fatan za a haɓaka shirin.",
        "normal": "Na al'ada",
        "original": "Asalin hoton",
        "password": "Kalmar sirri",
        "patient_id": "Lambar mara lafiya (shigar kafin loda hoto)",
        "patient_id_warning": "Da fatan za a shigar da lambar mara lafiya don ci gaba.",
        "pneumonia": "Ciwon huhu",
        "powered_by": "DARKMOOR LTD ne ya samar",
        "radiologist_confirmation": "Tabbatarwar likitan hoto:",
        "send_reset_link": "Aika hanyar sake saitin",
        "sign_up": "Yi rajista",
        "title": "🧠 MEDUSA – Na'urar Ganewar Cuta ta AI",
        "upgrade": "Haɓaka zuwa mara iyaka",
        "upload_prompt": "Sanya hotunan kirji, kwakwalwa ko huhu a ƙasa",
        "welcome": "Barka da zuwa",
    },
    "yo": {   # Yoruba
        "agree": "Mo gbà",
        "analysis": "Àtúpalẹ̀",
        "auto_detect": "Ìdánimọ̀ aládàáṣe",
        "benign": "Kò léwu",
        "brain_mri": "Àwòrán ọpọlọ (MRI)",
        "chest_xray": "Àwòrán àyà (X‑ray)",
        "correct_diagnosis": "Ìwádìí àrùn tó tọ̀nà:",
        "create_account": "Ṣí àkọọ́lẹ̀",
        "critical_finding": "⚠️ ÌWÁDÌÍ PÀTÀKÌ – ÀRÙN Ẹ̀DỌ̀FÒRÒ (ìgbẹ́kẹ̀lé gíga)",
        "disagree": "N kò gbà",
        "download_pdf_report": "Ṣe igbasilẹ ìròyìn PDF",
        "email": "Àdírẹ́ẹ̀sì ímeèlì",
        "footer": "MEDUSA · 850K sípín · CPU nìkan · v1.0",
        "forgot_password": "Gbàgbé ọ̀rọ̀ ìdásílẹ̀",
        "healthy": "Aláìsàn",
        "hospital_name": "Orúkọ ilé ìwòsàn / ilé ìtójú",
        "login": "Wọlé",
        "logout": "Jáde",
        "location": "Ibùdó",
        "lung_ct": "Àwòrán ẹ̀dọ̀fòrò (CT)",
        "malignant": "Ewu",
        "model_not_trained": "A kò tí ì kọ́ ẹ̀rọ náà",
        "modality_override": "Irú àwòrán (fi páà rẹ̀ bí ìdámọ̀ aládàáṣe bá kùnà):",
        "monthly_limit_reached": "Ààlà àyẹ̀wò oṣooṣù ti dé. Jọ̀wọ́ ṣe ìgbésókè.",
        "normal": "Dára",
        "original": "Àwòrán ìpilẹ̀ṣẹ̀",
        "password": "Ọ̀rọ̀ ìdásílẹ̀",
        "patient_id": "Nọ́mbà aláìsàn (ṣáájú kíkó àwòrán)",
        "patient_id_warning": "Jọ̀wọ́ fi nọ́mbà aláìsàn sílẹ̀ láti tẹ̀síwájú.",
        "pneumonia": "Àrùn ẹ̀dọ̀fòrò",
        "powered_by": "DARKMOOR LTD ló ṣe àgbékalẹ̀ rẹ̀",
        "radiologist_confirmation": "Ìfọwọ́sí oníṣègùn àwòrán:",
        "send_reset_link": "Fi ọ̀nà àtúnṣe ránṣẹ́",
        "sign_up": "Forúkọ sílẹ̀",
        "title": "🧠 MEDUSA – AI Ìṣègùn",
        "upgrade": "Ṣe ìgbésókè sí àìlópin",
        "upload_prompt": "Gbé àwọn àwòrán àyà, ọpọlọ tàbí ẹ̀dọ̀fòrò sí ìsàlẹ̀",
        "welcome": "Káàbọ̀",
    },
    "ig": {   # Igbo
        "agree": "Ekwetara m",
        "analysis": "Nnyocha",
        "auto_detect": "Nchọpụta akpaka",
        "benign": "Adịghị njọ",
        "brain_mri": "Ihe onyonyo ụbụrụ (MRI)",
        "chest_xray": "Ihe onyonyo obi (X‑ray)",
        "correct_diagnosis": "Nchọpụta ziri ezi:",
        "create_account": "Mepee akaụntụ",
        "critical_finding": "⚠️ NCHỌPỤTA DỊ OKÉ MKPA – ỌRỊA AKPARA (ntụkwasị obi dị elu)",
        "disagree": "Ekweghị m",
        "download_pdf_report": "Budata akụkọ PDF",
        "email": "Adreesị ozi‑e",
        "footer": "MEDUSA · 850K paramita · Naanị CPU · v1.0",
        "forgot_password": "Chefuru okwuntughe",
        "healthy": "Ahụ ike",
        "hospital_name": "Aha ụlọọgwụ / ụlọọgwụ",
        "login": "Banye",
        "logout": "Pụọ",
        "location": "Ebe",
        "lung_ct": "Ihe onyonyo akpa ume (CT)",
        "malignant": "Ọjọọ",
        "model_not_trained": "A zụbeghị ihe nlereanya",
        "modality_override": "Ụdị onyonyo (manye ma ọ bụrụ na nchọpụta akpaka adaa):",
        "monthly_limit_reached": "Oke nyocha nke ọnwa erutela. Biko kwalite.",
        "normal": "Nkịtị",
        "original": "Ihe onyonyo mbụ",
        "password": "Okwuntughe",
        "patient_id": "NJ onye ọrịa (tinye tupu ibulite)",
        "patient_id_warning": "Biko tinye NJ onye ọrịa iji gaa n'ihu.",
        "pneumonia": "Ọrịa akpara",
        "powered_by": "DARKMOOR LTD kwadoro",
        "radiologist_confirmation": "Nkwenye onye na‑ahụ maka ihe onyonyo:",
        "send_reset_link": "Ziga njikọ nrụpụta",
        "sign_up": "Debanye aha",
        "title": "🧠 MEDUSA – AI Ahụike",
        "upgrade": "Kwalite gaa na‑akparaghị ókè",
        "upload_prompt": "Tụba ihe onyonyo obi, ụbụrụ ma ọ bụ akpa ume n'okpuru",
        "welcome": "Nnọọ",
    },
    # --- 20+ more fully translated languages (Arabic, Chinese, Russian, etc.) ---
    "ar": {
        "agree": "موافق",
        "analysis": "تحليل",
        "auto_detect": "اكتشاف تلقائي",
        "benign": "حميد",
        "brain_mri": "رنين مغناطيسي للدماغ",
        "chest_xray": "أشعة صدر",
        "correct_diagnosis": "التشخيص الصحيح:",
        "create_account": "إنشاء حساب",
        "critical_finding": "⚠️ نتيجة حرجة – التهاب رئوي (ثقة عالية)",
        "disagree": "غير موافق",
        "download_pdf_report": "تنزيل تقرير PDF",
        "email": "بريد إلكتروني",
        "footer": "MEDUSA · 850K معلمة · وحدة معالجة مركزية فقط · v1.0",
        "forgot_password": "نسيت كلمة المرور",
        "healthy": "سليم",
        "hospital_name": "اسم المستشفى/العيادة",
        "login": "تسجيل الدخول",
        "logout": "تسجيل الخروج",
        "location": "الموقع",
        "lung_ct": "أشعة مقطعية للرئة",
        "malignant": "خبيث",
        "model_not_trained": "النموذج غير مدرب",
        "modality_override": "الطريقة (تجاوز إذا فشل الاكتشاف التلقائي):",
        "monthly_limit_reached": "تم الوصول إلى الحد الشهري للفحوص. يرجى الترقية.",
        "normal": "طبيعي",
        "original": "الصورة الأصلية",
        "password": "كلمة المرور",
        "patient_id": "رقم المريض (أدخل قبل التحميل)",
        "patient_id_warning": "يرجى إدخال رقم المريض للمتابعة.",
        "pneumonia": "التهاب رئوي",
        "powered_by": "مقدم من DARKMOOR LTD",
        "radiologist_confirmation": "تأكيد أخصائي الأشعة:",
        "send_reset_link": "إرسال رابط إعادة التعيين",
        "sign_up": "التسجيل",
        "title": "🧠 MEDUSA – ذكاء اصطناعي طبي",
        "upgrade": "الترقية إلى غير محدود",
        "upload_prompt": "أسقط صور الصدر أو الدماغ أو الرئة أدناه",
        "welcome": "مرحباً",
    },
    "zh-CN": {
        "agree": "同意",
        "analysis": "分析",
        "auto_detect": "自动检测",
        "benign": "良性",
        "brain_mri": "脑部 MRI",
        "chest_xray": "胸部 X 光",
        "correct_diagnosis": "正确诊断：",
        "create_account": "创建账户",
        "critical_finding": "⚠️ 危急发现 – 肺炎（高置信度）",
        "disagree": "不同意",
        "download_pdf_report": "下载 PDF 报告",
        "email": "电子邮件",
        "footer": "MEDUSA · 850K 参数 · 仅 CPU · v1.0",
        "forgot_password": "忘记密码",
        "healthy": "健康",
        "hospital_name": "医院/诊所名称",
        "login": "登录",
        "logout": "退出",
        "location": "位置",
        "lung_ct": "肺部 CT",
        "malignant": "恶性",
        "model_not_trained": "模型未训练",
        "modality_override": "模态（自动检测失败时强制）：",
        "monthly_limit_reached": "本月扫描次数已达上限。请升级。",
        "normal": "正常",
        "original": "原始图像",
        "password": "密码",
        "patient_id": "患者 ID（上传前输入）",
        "patient_id_warning": "请输入患者 ID 以继续。",
        "pneumonia": "肺炎",
        "powered_by": "由 DARKMOOR LTD 提供",
        "radiologist_confirmation": "放射科医生确认：",
        "send_reset_link": "发送重置链接",
        "sign_up": "注册",
        "title": "🧠 MEDUSA – 医疗 AI",
        "upgrade": "升级到无限制",
        "upload_prompt": "将胸部 X 光、脑部 MRI 或肺部 CT 片拖到下方",
        "welcome": "欢迎",
    },
    "ru": {
        "agree": "Согласен",
        "analysis": "Анализ",
        "auto_detect": "Автоопределение",
        "benign": "Доброкачественное",
        "brain_mri": "МРТ головного мозга",
        "chest_xray": "Рентген грудной клетки",
        "correct_diagnosis": "Правильный диагноз:",
        "create_account": "Создать аккаунт",
        "critical_finding": "⚠️ КРИТИЧЕСКАЯ НАХОДКА – ПНЕВМОНИЯ (высокая уверенность)",
        "disagree": "Не согласен",
        "download_pdf_report": "Скачать PDF‑отчёт",
        "email": "Электронная почта",
        "footer": "MEDUSA · 850K параметров · Только ЦП · v1.0",
        "forgot_password": "Забыли пароль",
        "healthy": "Здоров",
        "hospital_name": "Название больницы/клиники",
        "login": "Войти",
        "logout": "Выйти",
        "location": "Местоположение",
        "lung_ct": "КТ лёгких",
        "malignant": "Злокачественное",
        "model_not_trained": "Модель не обучена",
        "modality_override": "Модальность (принудительно, если автоопределение не сработало):",
        "monthly_limit_reached": "Достигнут месячный лимит сканирований. Обновите тариф.",
        "normal": "Норма",
        "original": "Исходное изображение",
        "password": "Пароль",
        "patient_id": "ID пациента (введите перед загрузкой)",
        "patient_id_warning": "Введите ID пациента, чтобы продолжить.",
        "pneumonia": "Пневмония",
        "powered_by": "Разработано DARKMOOR LTD",
        "radiologist_confirmation": "Подтверждение радиолога:",
        "send_reset_link": "Отправить ссылку для сброса",
        "sign_up": "Регистрация",
        "title": "🧠 MEDUSA – Медицинский ИИ",
        "upgrade": "Перейти на безлимитный",
        "upload_prompt": "Перетащите снимки грудной клетки, МРТ мозга или КТ лёгких ниже",
        "welcome": "Добро пожаловать",
    },
    # Add more languages as needed...
}

# -------------------------------------------------------------------
# Fallback helper: returns the translated string for lang_code and key.
# If lang_code or key is missing, fallback to English.
# -------------------------------------------------------------------
def get_translation(lang_code: str, key: str) -> str:
    """Return translated string, falling back to English if not available."""
    # Try requested language
    if lang_code in TRANSLATIONS and key in TRANSLATIONS[lang_code]:
        return TRANSLATIONS[lang_code][key]
    # Fallback to English
    if "en" in TRANSLATIONS and key in TRANSLATIONS["en"]:
        return TRANSLATIONS["en"][key]
    # Last resort: return the key itself
    return key